### ISSUE TITLE
Would it be possible to see in the browser a continuous response from polling data generated by tail -f, journalctl -f or similar?

### ISSUE THREAD

**Issue by q2dg** [BBVA/kapow#108]
I've seen examples but I've only seen the use or journalctl -n1000, but that's not what I want
Thanks!

**Comment by panchoh** [comment]
Sure thing!

Consider for example `dmesg.pow`:
```shell
kapow route add /dmesg -c 'dmesg -w | kapow set /response/body'
```

Now, running `kapow server` on it:

```shell
$ kapow server dmesg.pow
```
The output can be checked with `curl` or with a browser:
```shell
$ curl http://localhost:8080/dmesg
```
Try inserting and removing a usb device a few times, and eventually you'll get the output updated.
The updates don't get sent immediately if they are small, because there is some buffering involved, which for now cannot be managed by the user.  We'll tackle this in a future update, though.

Hope that it helps!

(feel feel to either request more clarifications, or to close the issue if you are satisfied with this reply).

Happy hacking.

**Comment by q2dg** [comment]
Thanks for your so fast answer!

Well, it works somewhat, but in a very erratic manner. As you have said, it's not real-time (that is, web page is not updated automagically) but this wouldn't be a problem if manually forcing the upgrade of the web page (via F5 for instance) showed correct results. However,  they're not: sometimes shown lines arrive until nearly the last one in terminal's output but sometimes they don't. It's very fragile.

Anyway, I know it's a difficult issue and maybe it doesn't worthy. 
I'll close the issue but feel free to reopen it if you consider
Thanks!

**Comment by nilp0inter** [comment]
@q2dg , the erratic behavior you are referring to is due to the Go's http module managing the output buffer in an automatic fashion. We will support the configuration of the underlying buffer to support per-line buffering (among others) which is the way users expect command-line tools to behave.

Stay tuned for updates!
